version: '3.9'

services:
  backend:
    build:
      context: ./doctor-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=doctor_db
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./doctor-backend:/app

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: doctor_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./gateway:/app

volumes:
  db-data:
